{{- if .Values.rbac.create -}}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
  {{- if .Values.resources.certificatesigningrequests }}
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.configmaps }}
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.cronjobs }}
  - apiGroups: ["batch"]
    resources:
      - cronjobs
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.daemonsets }}
  - apiGroups: ["extensions", "apps"]
    resources:
      - daemonsets
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.deployments }}
  - apiGroups: ["extensions", "apps"]
    resources:
      - deployments
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.endpoints }}
  - apiGroups: [""]
    resources:
      - endpoints
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.horizontalpodautoscalers }}
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.ingresses }}
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.jobs }}
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.limitranges }}
  - apiGroups: [""]
    resources:
      - limitranges
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.mutatingwebhookconfigurations }}
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.namespaces }}
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.networkpolicies }}
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.nodes }}
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.persistentvolumeclaims }}
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.persistentvolumes }}
  - apiGroups: [""]
    resources:
      - persistentvolumes
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.poddisruptionbudgets }}
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.pods }}
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.replicasets }}
  - apiGroups: ["extensions", "apps"]
    resources:
      - replicasets
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.replicationcontrollers }}
  - apiGroups: [""]
    resources:
      - replicationcontrollers
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.resourcequotas }}
  - apiGroups: [""]
    resources:
      - resourcequotas
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.secrets }}
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.services }}
  - apiGroups: [""]
    resources:
      - services
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.statefulsets }}
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.storageclasses }}
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.verticalpodautoscalers }}
  - apiGroups: ["autoscaling.k8s.io"]
    resources:
      - verticalpodautoscalers
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.validatingwebhookconfigurations }}
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
    verbs: ["list", "watch"]
  {{- end }}
  {{- if .Values.resources.volumeattachments }}
  - apiGroups: ["storage.k8s.io"]
    resources:
      - volumeattachments
    verbs: ["list", "watch"]
  {{- end }}
{{- end }}
